# Etapa de build
FROM golang:1.21 AS builder
WORKDIR /app
COPY . .
RUN go build -o nuvem ./cmd/nuvem/main.go

# Etapa de execução
FROM debian:latest
WORKDIR /root/
COPY --from=builder /app/nuvem .
CMD ["./nuvem"]
