# Etapa de build
FROM golang:1.24.1 AS builder
WORKDIR /app
COPY . .
ENV CGO_ENABLED=0
RUN go build -o ponto ./cmd/ponto/main.go  # Compila o binário do ponto

# Etapa de execução
FROM debian:latest
WORKDIR /app

# Copia o binário compilado
COPY --from=builder /app/ponto .

# Define o comando padrão para o container
CMD ["./ponto"]