# Etapa de build
FROM golang:1.21 AS builder
WORKDIR /app
COPY . .
RUN go build -o ponto ./cmd/ponto/main.go

# Etapa de execução
FROM debian:latest
WORKDIR /root/
COPY --from=builder /app/ponto .
CMD ["./ponto"]
